#!/usr/env python
#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: unitmgr.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxWindows' modules
from wxPython.wx import *

# Window functions

ID_NOTEBOOK = 10000
ID_TEXT = 10001
ID_UNIT_NAME = 10002
ID_UNIT_TYPE = 10003
ID_UNIT_SCALE = 10004
ID_UNIT_OFFSET = 10005
ID_OPERATION = 10006
ID_NOTE = 10007
ID_LINE = 10008
ID_CONVERT_FROM_VALUE = 10009
ID_FROM_UNIT_NAME = 10010
ID_CONVERTED_VALUE = 10011
ID_TO_UNIT_NAME = 10012
ID_TO_UNIT_ITEM_CHOICE = 10013
ID_TO_UNIT_SET_CHOICE = 10014
ID_SAVE = 10015
ID_QUIT = 10016

def ManagerDialog( parent, call_fit = true, set_sizer = true ):
    item0 = wxFlexGridSizer( 3, 0, 0, 10 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 0 )
    
    item1 = wxFlexGridSizer( 0, 2, 0, 0 )
    item1.AddGrowableCol( 0 )
    item1.AddGrowableRow( 0 )
    
    item3 = wxNotebook( parent, ID_NOTEBOOK, wxDefaultPosition, wxSize(200,160), 0 )
    item2 = wxNotebookSizer( item3 )

    item4 = wxPanel( item3, -1 )
    UnitItemsPane( item4, false )
    item3.AddPage( item4, "Unit Items" )

    item5 = wxPanel( item3, -1 )
    UnitTypePane( item5, false )
    item3.AddPage( item5, "Unit Types" )

    item6 = wxPanel( item3, -1 )
    UnitSetPane( item6, false )
    item3.AddPage( item6, "Unit Sets" )

    item1.AddSizer( item2, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item8 = wxStaticBox( parent, -1, "Unit Item" )
    item7 = wxStaticBoxSizer( item8, wxHORIZONTAL )
    
    item9 = wxFlexGridSizer( 0, 2, 0, 0 )
    item9.AddGrowableCol( 1 )
    
    item10 = wxStaticText( parent, ID_TEXT, "Name (ID)", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item10, 0, wxALIGN_CENTRE|wxALL, 0 )

    item11 = wxTextCtrl( parent, ID_UNIT_NAME, "", wxDefaultPosition, wxSize(200,-1), 0 )
    item9.AddWindow( item11, 0, wxALIGN_CENTRE|wxALL, 0 )

    item12 = wxStaticText( parent, ID_TEXT, "Unt Type", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item12, 0, wxALIGN_CENTRE|wxALL, 0 )

    item13 = wxTextCtrl( parent, ID_UNIT_TYPE, "", wxDefaultPosition, wxSize(80,-1), 0 )
    item9.AddWindow( item13, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 )

    item14 = wxStaticText( parent, ID_TEXT, "Scale", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item14, 0, wxALIGN_CENTRE|wxALL, 0 )

    item15 = wxTextCtrl( parent, ID_UNIT_SCALE, "", wxDefaultPosition, wxSize(80,-1), 0 )
    item9.AddWindow( item15, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 )

    item16 = wxStaticText( parent, ID_TEXT, "Offset", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item16, 0, wxALIGN_CENTRE|wxALL, 0 )

    item17 = wxTextCtrl( parent, ID_UNIT_OFFSET, "", wxDefaultPosition, wxSize(80,-1), 0 )
    item9.AddWindow( item17, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 )

    item18 = wxStaticText( parent, ID_TEXT, "Operation", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item18, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 0 )

    item19 = wxTextCtrl( parent, ID_OPERATION, "", wxDefaultPosition, wxSize(80,40), wxTE_MULTILINE )
    item9.AddWindow( item19, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 )

    item20 = wxStaticText( parent, ID_TEXT, "Note", wxDefaultPosition, wxDefaultSize, 0 )
    item9.AddWindow( item20, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 0 )

    item21 = wxTextCtrl( parent, ID_NOTE, "", wxDefaultPosition, wxSize(80,40), wxTE_MULTILINE )
    item9.AddWindow( item21, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 )

    item7.AddSizer( item9, 0, wxALIGN_CENTRE|wxALL, 5 )

    item1.AddSizer( item7, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item0.AddSizer( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item22 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(20,-1), wxLI_HORIZONTAL )
    item0.AddWindow( item22, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item23 = wxBoxSizer( wxVERTICAL )
    
    item24 = wxFlexGridSizer( 1, 0, 0, 0 )
    item24.AddGrowableCol( 0 )
    item24.AddGrowableCol( 2 )
    
    item26 = wxStaticBox( parent, -1, "Convert:" )
    item26.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) )
    item25 = wxStaticBoxSizer( item26, wxHORIZONTAL )
    
    item27 = wxBoxSizer( wxVERTICAL )
    
    item28 = wxBoxSizer( wxHORIZONTAL )
    
    item29 = wxTextCtrl( parent, ID_CONVERT_FROM_VALUE, "", wxDefaultPosition, wxSize(150,-1), 0 )
    item28.AddWindow( item29, 0, wxALIGN_CENTRE|wxALL, 5 )

    item30 = wxStaticText( parent, ID_FROM_UNIT_NAME, "label", wxDefaultPosition, wxSize(150,-1), wxST_NO_AUTORESIZE )
    item30.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) )
    item28.AddWindow( item30, 0, wxADJUST_MINSIZE|wxALIGN_CENTRE|wxALL, 5 )

    item27.AddSizer( item28, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 )

    item31 = wxStaticText( parent, ID_TEXT, "To: ", wxDefaultPosition, wxDefaultSize, 0 )
    item31.SetFont( wxFont( 10, wxROMAN, wxNORMAL, wxBOLD ) )
    item27.AddWindow( item31, 0, wxADJUST_MINSIZE|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item32 = wxBoxSizer( wxHORIZONTAL )
    
    item33 = wxStaticText( parent, ID_CONVERTED_VALUE, "__", wxDefaultPosition, wxSize(150,-1), wxST_NO_AUTORESIZE )
    item33.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) )
    item32.AddWindow( item33, 0, wxADJUST_MINSIZE|wxALIGN_CENTRE|wxALL, 5 )

    item34 = wxStaticText( parent, ID_TO_UNIT_NAME, "label", wxDefaultPosition, wxSize(150,-1), wxST_NO_AUTORESIZE )
    item34.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) )
    item32.AddWindow( item34, 0, wxADJUST_MINSIZE|wxALIGN_CENTRE|wxALL, 5 )

    item27.AddSizer( item32, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 )

    item25.AddSizer( item27, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 0 )

    item35 = wxBoxSizer( wxVERTICAL )
    
    item36 = wxBoxSizer( wxHORIZONTAL )
    
    item37 = wxStaticText( parent, ID_TEXT, "Unit", wxDefaultPosition, wxSize(80,-1), 0 )
    item37.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) )
    item36.AddWindow( item37, 0, wxALIGN_CENTRE|wxALL, 5 )

    item38 = wxChoice( parent, ID_TO_UNIT_ITEM_CHOICE, wxDefaultPosition, wxSize(100,-1), 
        ["ChoiceItem","Item","Item","Item","Item","Item"] , 0 )
    item36.AddWindow( item38, 0, wxALIGN_CENTRE, 5 )

    item35.AddSizer( item36, 0, wxALIGN_CENTER_VERTICAL, 5 )

    item39 = wxBoxSizer( wxHORIZONTAL )
    
    item40 = wxStaticText( parent, ID_TEXT, "Set", wxDefaultPosition, wxSize(80,-1), 0 )
    item40.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxBOLD ) )
    item39.AddWindow( item40, 0, wxALIGN_CENTRE|wxALL, 5 )

    item41 = wxChoice( parent, ID_TO_UNIT_SET_CHOICE, wxDefaultPosition, wxSize(100,100), 
        ["ChoiceItem","Item","Item","Item","Item","Item"] , 0 )
    item39.AddWindow( item41, 0, wxALIGN_CENTRE, 5 )

    item35.AddSizer( item39, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 5 )

    item25.AddSizer( item35, 0, wxALIGN_BOTTOM|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item24.AddSizer( item25, 0, wxALIGN_CENTER_VERTICAL, 5 )

    item42 = wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxDefaultSize, wxLI_VERTICAL )
    item42.SetFont( wxFont( 8, wxROMAN, wxNORMAL, wxNORMAL ) )
    item24.AddWindow( item42, 0, wxGROW, 0 )

    item43 = wxBoxSizer( wxVERTICAL )
    
    item44 = wxButton( parent, ID_SAVE, "Save", wxDefaultPosition, wxDefaultSize, 0 )
    item43.AddWindow( item44, 0, wxALIGN_CENTRE|wxALL, 5 )

    item45 = wxButton( parent, ID_QUIT, "Quit", wxDefaultPosition, wxDefaultSize, 0 )
    item43.AddWindow( item45, 0, wxALIGN_CENTRE|wxALL, 5 )

    item24.AddSizer( item43, 0, wxALIGN_CENTRE|wxALL, 5 )

    item23.AddSizer( item24, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 )

    item0.AddSizer( item23, 0, wxGROW, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_ITEMSLIST = 10017

def UnitItemsPane( parent, call_fit = true, set_sizer = true ):
    item0 = wxFlexGridSizer( 0, 1, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableRow( 0 )
    
    item1 = wxListBox( parent, ID_ITEMSLIST, wxDefaultPosition, wxSize(300,100), 
        ["ListItem"] , wxLB_SINGLE )
    item1.SetFont( wxFont( 9, wxMODERN, wxNORMAL, wxNORMAL ) )
    item0.AddWindow( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_TYPELIST = 10018
ID_TYPEUNITLIST = 10019

def UnitTypePane( parent, call_fit = true, set_sizer = true ):
    item0 = wxFlexGridSizer( 0, 2, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableCol( 1 )
    item0.AddGrowableRow( 0 )
    
    item1 = wxListBox( parent, ID_TYPELIST, wxDefaultPosition, wxSize(200,100), [], wxLB_SINGLE )
    item1.SetFont( wxFont( 9, wxMODERN, wxNORMAL, wxNORMAL ) )
    item0.AddWindow( item1, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item2 = wxListBox( parent, ID_TYPEUNITLIST, wxDefaultPosition, wxSize(150,100), [], wxLB_SINGLE )
    item2.SetFont( wxFont( 9, wxMODERN, wxNORMAL, wxNORMAL ) )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_SETLIST = 10020
ID_SETUNITLIST = 10021

def UnitSetPane( parent, call_fit = true, set_sizer = true ):
    item0 = wxFlexGridSizer( 0, 2, 0, 0 )
    item0.AddGrowableCol( 0 )
    item0.AddGrowableCol( 1 )
    item0.AddGrowableRow( 0 )
    
    item1 = wxListBox( parent, ID_SETLIST, wxDefaultPosition, wxSize(150,100), [], wxLB_SINGLE )
    item1.SetFont( wxFont( 9, wxMODERN, wxNORMAL, wxNORMAL ) )
    item0.AddWindow( item1, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item2 = wxListBox( parent, ID_SETUNITLIST, wxDefaultPosition, wxSize(250,100), [], wxLB_SINGLE )
    item2.SetFont( wxFont( 9, wxMODERN, wxNORMAL, wxNORMAL ) )
    item0.AddWindow( item2, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_EDIT_UNIT_NAME = 10022
ID_EDIT_UNIT_TYPE = 10023
ID_EDIT_UNIT_SCALE = 10024
ID_EDIT_UNIT_OFFSET = 10025
ID_EDIT_UNIT_OP = 10026
ID_EDIT_UNIT_BASEUNIT = 10027
ID_EDIT_UNIT_NOTE = 10028
ID_OK = 10029
ID_CANCEL = 10030

def EditUnitDialog( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item2 = wxStaticBox( parent, -1, "Unit Item Description" )
    item2.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item1 = wxStaticBoxSizer( item2, wxVERTICAL )
    
    item3 = wxBoxSizer( wxHORIZONTAL )
    
    item4 = wxBoxSizer( wxVERTICAL )
    
    item5 = wxStaticText( parent, ID_TEXT, "Name", wxDefaultPosition, wxSize(-1,25), 0 )
    item5.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item4.AddWindow( item5, 0, wxALIGN_CENTER_VERTICAL, 5 )

    item6 = wxStaticText( parent, ID_TEXT, "Unit Type", wxDefaultPosition, wxSize(-1,25), 0 )
    item6.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item4.AddWindow( item6, 0, wxALIGN_CENTER_VERTICAL|wxTOP, 5 )

    item7 = wxStaticText( parent, ID_TEXT, "Scale", wxDefaultPosition, wxSize(-1,20), 0 )
    item7.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item4.AddWindow( item7, 0, wxALIGN_CENTER_VERTICAL|wxTOP, 5 )

    item8 = wxStaticText( parent, ID_TEXT, "Offset", wxDefaultPosition, wxSize(-1,25), 0 )
    item8.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item4.AddWindow( item8, 0, wxALIGN_CENTER_VERTICAL|wxTOP, 5 )

    item9 = wxStaticText( parent, ID_TEXT, "Operation", wxDefaultPosition, wxSize(-1,25), 0 )
    item9.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item4.AddWindow( item9, 0, wxALIGN_CENTER_VERTICAL|wxTOP, 5 )

    item10 = wxStaticText( parent, ID_TEXT, "Base Unit", wxDefaultPosition, wxSize(-1,25), 0 )
    item10.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item4.AddWindow( item10, 0, wxALIGN_CENTER_VERTICAL|wxTOP, 5 )

    item3.AddSizer( item4, 0, wxALIGN_CENTER_HORIZONTAL|wxRIGHT|wxTOP|wxBOTTOM, 5 )

    item11 = wxBoxSizer( wxVERTICAL )
    
    item12 = wxTextCtrl( parent, ID_EDIT_UNIT_NAME, "", wxDefaultPosition, wxSize(200,25), 0 )
    item11.AddWindow( item12, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxLEFT, 5 )

    item13 = wxChoice( parent, ID_EDIT_UNIT_TYPE, wxDefaultPosition, wxSize(200,25), 
        ["","","","",""] , 0 )
    item11.AddWindow( item13, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 5 )

    item14 = wxTextCtrl( parent, ID_EDIT_UNIT_SCALE, "", wxDefaultPosition, wxSize(200,25), 0 )
    item11.AddWindow( item14, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 5 )

    item15 = wxTextCtrl( parent, ID_EDIT_UNIT_OFFSET, "", wxDefaultPosition, wxSize(200,25), 0 )
    item11.AddWindow( item15, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 5 )

    item16 = wxChoice( parent, ID_EDIT_UNIT_OP, wxDefaultPosition, wxSize(200,25), 
        ["BaseUnit = scale * UnitItem + offset ","BaseUnit = scale / UnitItem + offset ","BaseUnit = scale * UnitItem^2 + offset ","BaseUnit = scale / UnitItem^2 + offset ","BaseUnit = scale / UnitItem^2 + offset "] , 0 )
    item11.AddWindow( item16, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL, 5 )

    item17 = wxStaticText( parent, ID_EDIT_UNIT_BASEUNIT, "text", wxDefaultPosition, wxSize(200,25), 0 )
    item17.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item11.AddWindow( item17, 0, wxALIGN_CENTER_VERTICAL|wxLEFT|wxTOP, 5 )

    item3.AddSizer( item11, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item1.AddSizer( item3, 0, wxALL, 5 )

    item18 = wxStaticText( parent, ID_TEXT, "Note", wxDefaultPosition, wxDefaultSize, 0 )
    item18.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item1.AddWindow( item18, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 5 )

    item19 = wxTextCtrl( parent, ID_EDIT_UNIT_NOTE, "", wxDefaultPosition, wxSize(300,25), 0 )
    item1.AddWindow( item19, 0, wxALIGN_CENTER_VERTICAL, 5 )

    item0.AddSizer( item1, 0, wxALIGN_CENTRE|wxALL, 5 )

    item20 = wxBoxSizer( wxHORIZONTAL )
    
    item21 = wxButton( parent, ID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item20.AddWindow( item21, 0, wxALIGN_CENTRE|wxALL, 5 )

    item22 = wxButton( parent, ID_CANCEL, "Cancel", wxDefaultPosition, wxDefaultSize, 0 )
    item20.AddWindow( item22, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item20, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_EDIT_NAME = 10031
ID_SETTYPELIST = 10032
ID_USE_UNIT = 10033

def EditSetDlg( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item2 = wxStaticBox( parent, -1, "Unit Set" )
    item2.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item1 = wxStaticBoxSizer( item2, wxVERTICAL )
    
    item3 = wxBoxSizer( wxHORIZONTAL )
    
    item4 = wxStaticText( parent, ID_TEXT, "Name:", wxDefaultPosition, wxDefaultSize, 0 )
    item4.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item3.AddWindow( item4, 0, wxALIGN_CENTRE|wxALL, 5 )

    item5 = wxTextCtrl( parent, ID_EDIT_NAME, "", wxDefaultPosition, wxSize(200,-1), 0 )
    item3.AddWindow( item5, 0, wxALIGN_CENTRE|wxALL, 5 )

    item1.AddSizer( item3, 0, wxALIGN_CENTRE|wxALL, 5 )

    item6 = wxListBox( parent, ID_SETTYPELIST, wxDefaultPosition, wxSize(250,100), [], wxLB_SINGLE )
    item6.SetFont( wxFont( 9, wxMODERN, wxNORMAL, wxNORMAL ) )
    item1.AddWindow( item6, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 )

    item7 = wxBoxSizer( wxHORIZONTAL )
    
    item8 = wxStaticText( parent, ID_TEXT, "Use Unit:", wxDefaultPosition, wxDefaultSize, 0 )
    item8.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item7.AddWindow( item8, 0, wxALIGN_CENTRE|wxALL, 5 )

    item9 = wxChoice( parent, ID_USE_UNIT, wxDefaultPosition, wxSize(200,-1), 
        ["","","","",""] , 0 )
    item7.AddWindow( item9, 0, wxALIGN_CENTRE|wxALL, 5 )

    item1.AddSizer( item7, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item1, 0, wxALL, 5 )

    item10 = wxBoxSizer( wxHORIZONTAL )
    
    item11 = wxButton( parent, ID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item10.AddWindow( item11, 0, wxALIGN_CENTRE|wxALL, 5 )

    item12 = wxButton( parent, ID_CANCEL, "Cancel", wxDefaultPosition, wxDefaultSize, 0 )
    item10.AddWindow( item12, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item10, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

ID_EDITTYPENAME = 10034
ID_EDITTYPEBASE = 10035

def EditTypeDlg( parent, call_fit = true, set_sizer = true ):
    item0 = wxBoxSizer( wxVERTICAL )
    
    item2 = wxStaticBox( parent, -1, "Unit Type Description" )
    item2.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item1 = wxStaticBoxSizer( item2, wxVERTICAL )
    
    item3 = wxGridSizer( 0, 2, 0, 0 )
    
    item4 = wxStaticText( parent, ID_TEXT, "Name", wxDefaultPosition, wxDefaultSize, 0 )
    item4.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item3.AddWindow( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item5 = wxTextCtrl( parent, ID_EDITTYPENAME, "", wxDefaultPosition, wxSize(200,-1), 0 )
    item3.AddWindow( item5, 0, wxALIGN_CENTRE|wxALL, 5 )

    item6 = wxStaticText( parent, ID_TEXT, "Initial Unit Name", wxDefaultPosition, wxDefaultSize, 0 )
    item6.SetFont( wxFont( 12, wxROMAN, wxNORMAL, wxNORMAL ) )
    item3.AddWindow( item6, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 )

    item7 = wxTextCtrl( parent, ID_EDITTYPEBASE, "", wxDefaultPosition, wxSize(200,-1), 0 )
    item3.AddWindow( item7, 0, wxALIGN_CENTRE|wxALL, 5 )

    item1.AddSizer( item3, 0, wxALIGN_CENTRE|wxALL, 5 )

    item8 = wxBoxSizer( wxHORIZONTAL )
    
    item9 = wxButton( parent, ID_OK, "OK", wxDefaultPosition, wxDefaultSize, 0 )
    item8.AddWindow( item9, 0, wxALIGN_CENTRE|wxALL, 5 )

    item10 = wxButton( parent, ID_CANCEL, "Cancel", wxDefaultPosition, wxDefaultSize, 0 )
    item8.AddWindow( item10, 0, wxALIGN_CENTRE|wxALL, 5 )

    item1.AddSizer( item8, 0, wxALIGN_CENTRE|wxALL, 5 )

    item0.AddSizer( item1, 0, wxALIGN_CENTRE|wxALL, 5 )

    if set_sizer == true:
        parent.SetAutoLayout( true )
        parent.SetSizer( item0 )
        if call_fit == true:
            item0.Fit( parent )
            item0.SetSizeHints( parent )
    
    return item0

# Menu bar functions

ID_CHANGE_USER = 10036
ID_MENU = 10037
ID_ABOUT = 10038

def MyMenuBarFunc():
    item0 = wxMenuBar()
    
    item1 = wxMenu()
    item1.Append( ID_SAVE, "Save\tCtrl-S", "" )
    item1.Append( ID_CHANGE_USER, "Change User Directory...", "" )
    item1.Append( ID_QUIT, "Quit\tCtrl-Q", "" )
    item0.Append( item1, "File" )
    
    item2 = wxMenu()
    item0.Append( item2, "Help" )
    
    return item0

# Bitmap functions


# End of generated file
